server:
  port: ${APPLICATION_HTTP_PORT:9996}
  max-http-header-size: 64KB

spring:
  profiles:
    active: test
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 1000
  freemarker:
    charset: utf-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: pinesid
    password: pinespass
    url: jdbc:mysql://10.159.5.251:3306/study?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
  freemarker:
    cache: true
  devtools:
    livereload:
      enabled: true
  jpa:
    database: mysql